#!/bin/sh
exec >/dev/console 2>&1
export TERM=linux
export PS1='initramfs-test:\w\$ '
stty sane
echo "made it to the rootfs! Powering down."
echo OK $(ls /dev/.initramfs/*.ifcfg) > /dev/sda
#sh -i
poweroff -f
